export const actionTypes = {
  CHANGE_SEARCH_FIELD: "CHANGE_SEARCH_FIELD",
  REQUEST_ROBOTS_FAILED: "REQUEST_ROBOTS_FAILED",
  REQUEST_ROBOTS_SUCCESS: "REQUEST_ROBOTS_SUCCESS",
  REQUEST_ROBOTS_PENDING: "REQUEST_ROBOTS_PENDING",
  FETCH_ALBUMS_AND_USERS_PENDING: "FETCH_ALBUMS_AND_USERS_PENDING",
  FETCH_ALBUMS_AND_USERS_SUCCESS: "FETCH_ALBUMS_AND_USERS_SUCCESS",
  FETCH_ALBUMS_AND_USERS_FAILED: "FETCH_ALBUMS_AND_USERS_FAILED",
};
